import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import ScrollDown from "./components/ScrollDown";
import { courier } from "./fonts/fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${courier.className} relative antialiased w-full h-screen`}
        >
        <Header/>
        <div className="pb-12 pt-28">
        {children}
        </div>
        <Footer/>
        <ScrollDown/>
      </body>
    </html>
  );
}
